# Generated by Django 6.0.1 on 2026-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_doramanews_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoramaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
