# Generated by Django 6.0.1 on 2026-01-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_doramanews_options_alter_doramavideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doramavideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Загрузить видео файл'),
        ),
        migrations.AlterField(
            model_name='doramavideo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Или ссылка на YouTube'),
        ),
    ]
